# Simple Document Generator Configuration
# Minimal configuration for testing state persistence and file generation

# Default script engine
default_engine = "lua"

# Engine configuration
[engines.lua]
enable_debug = true
timeout_ms = 120000  # 2 minutes for workflow completion

# Provider configurations
[providers]
default_provider = "openai"

[providers.providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
default_model = "gpt-4o-mini"
timeout_seconds = 60

[providers.providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-3-haiku-20240307"
timeout_seconds = 60

# Runtime configuration
[runtime]
max_concurrent_scripts = 5
script_timeout_seconds = 300
enable_streaming = true

[runtime.security]
allow_file_access = true
allow_network_access = true
allow_process_spawn = false

# State persistence - CRITICAL for this example
[runtime.state_persistence]
enabled = true
backend_type = "memory"
max_state_size_bytes = 10000000

# Session management (optional for this example)
[runtime.sessions]
enabled = false

# Debug configuration
[runtime.debug]
enabled = true
level = "info"
capture_output = true

# Tool configurations
[tools.file_operations]
allowed_paths = [
    "/tmp/doc-gen-test",
    "/tmp"
]
atomic_writes = true
max_file_size = 10485760