# Universal Layer Configuration - Research Collector with RAG
# Simple configuration for everyday research needs with knowledge persistence

[runtime]
name = "research-collector"
description = "Universal research automation with knowledge base"

# Single provider with fallback for reliability
[providers.openai]
name = "openai"
api_key_env = "OPENAI_API_KEY"
api_base = "https://api.openai.com/v1"
default_model = "gpt-4o-mini"
timeout_seconds = 30

# Basic tools for research
[tools]
file_operations = { enabled = true }
web_search = { enabled = true }
http_request = { enabled = true }
text_manipulator = { enabled = true }

# Simple workflow configuration
[workflows]
enabled = true
max_concurrent = 2  # Simple parallel search
timeout_seconds = 60

# No state for universal simplicity
[state]
enabled = false

# No sessions for basic research
[sessions]
enabled = false

# No events tracking
[events]
enabled = false

# RAG configuration for knowledge persistence
[rag]
enabled = true
provider = "openai"
embedding_model = "text-embedding-ada-002"
vector_dimensions = 1536
default_collection = "research_knowledge"
chunk_size = 500
chunk_overlap = 50
persistence_path = "/tmp/research-rag-storage"