[runtime]
version = "0.6.0"

[runtime.state_persistence]
enabled = true
backend = "sqlite"
path = "./test-state.db"

[runtime.logging]
level = "debug"

[providers]
[providers.openai]
api_key = "${OPENAI_API_KEY}"
model = "gpt-4o-mini"