# Test configuration with only OpenAI
default_engine = "lua"

[engines.lua]
stdlib_level = "full"
sandbox_mode = false

[providers]
default_provider = "openai"

[providers.providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4"
max_tokens = 2048

[runtime]
max_concurrent_scripts = 10
script_timeout_seconds = 300
enable_streaming = true

[runtime.security]
allow_file_access = false
allow_network_access = true
allow_process_spawn = false