[package]
name = "llmspell-cli"
description = "Command-line interface for rs-llmspell"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "llmspell"
path = "src/main.rs"

[dependencies]
llmspell-core = { path = "../llmspell-core" }
llmspell-config = { path = "../llmspell-config" }
llmspell-bridge = { path = "../llmspell-bridge" }
llmspell-providers = { path = "../llmspell-providers" }
llmspell-utils = { path = "../llmspell-utils" }
llmspell-state-persistence = { path = "../llmspell-state-persistence" }
llmspell-storage = { path = "../llmspell-storage" }
llmspell-repl = { path = "../llmspell-repl" }
llmspell-debug = { path = "../llmspell-debug" }
llmspell-engine = { path = "../llmspell-engine" }
tokio.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures.workspace = true
dirs = "5.0"
indicatif = "0.17"
tokio-stream = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }
once_cell = { workspace = true }
uuid = { workspace = true }
dialoguer = "0.11"
async-trait = { workspace = true }
rustyline = "14.0"
tempfile = "3.8"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
tempfile = "3.8"
serial_test = { workspace = true }