# Code Review Assistant - Minimal Configuration
# Only what's actually needed for the application to run

# Lua engine settings
[engines.lua]
security_level = "Safe"

# File operation permissions
[tools.file_operations]
allowed_paths = [
    "/tmp"
]