# Basic State Persistence Configuration
# Purpose: Minimal configuration for basic state operations examples
# Usage: ./llmspell -c examples/script-users/configs/basic.toml run <script>

# Default script engine
default_engine = "lua"

# Engine configuration
[engines.lua]
stdlib_level = "full"

# No providers configured for basic examples
[providers]
# Empty section - no providers needed

# Runtime configuration
[runtime]
log_level = "info"

# State persistence configuration
[runtime.state_persistence]
enabled = true
backend_type = "memory"  # In-memory for quick examples
max_state_size_bytes = 10_000_000  # 10MB
migration_enabled = false
backup_enabled = false

# Example metadata (non-standard section, ignored by runtime)
[example]
name = "Basic State Operations"
description = "Demonstrates core state persistence functionality"
features = ["basic_operations", "scoping", "data_types"]