# Basic State Persistence Configuration
# Purpose: Minimal configuration for basic state operations examples
# Usage: ./llmspell -c examples/state_persistence/configs/basic.toml run <script>

[state]
enabled = true
backend = "memory"  # In-memory for quick examples

[state.performance]
cache_size = 10_000_000  # 10MB cache
fast_path_enabled = true
async_hooks = true

# Logging configuration for examples
[logging]
level = "info"
format = "pretty"

# Example metadata
[example]
name = "Basic State Operations"
description = "Demonstrates core state persistence functionality"
features = ["basic_operations", "scoping", "data_types"]