# Example provider configuration
# This demonstrates how to configure LLM providers for LLMSpell

# Default script engine
default_engine = "lua"

# Provider configuration
[providers]
default_provider = "openai"

[providers.providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4"

[providers.providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-opus-20240229"

# Engine configuration (optional)
[engines.lua]
security_level = "safe"

[engines.javascript]
security_level = "safe"

# Runtime configuration (optional)
[runtime]
log_level = "info"