# Multi-Tenant RAG Configuration Template
# This configuration enables tenant isolation for RAG operations
# Each tenant's data is completely isolated from others

[rag]
# Enable RAG functionality
enabled = true

# IMPORTANT: Enable multi-tenant support for data isolation
multi_tenant = true

[rag.vector_storage]
# Vector dimensions - ensure consistency across all tenants
dimensions = 768  # Using a larger model for better accuracy

# Use HNSW for production multi-tenant scenarios
backend = "hnsw"

# Persistence is recommended for multi-tenant to avoid data loss
persistence_path = "./data/rag/vectors"

# Larger limits for multi-tenant scenarios
[rag.vector_storage.hnsw]
m = 32                    # More connections for better recall
ef_construction = 400     # Higher quality index construction
ef_search = 100          # Better search quality
max_elements = 10000000  # Support many tenants (10M vectors)
metric = "cosine"
allow_replace_deleted = true  # Important for tenant cleanup
num_threads = 8          # More threads for concurrent tenant operations

[rag.embedding]
# Provider configuration for multi-tenant
default_provider = "openai"

# Aggressive caching for multi-tenant efficiency
cache_enabled = true
cache_size = 50000       # Larger cache for multiple tenants
cache_ttl_seconds = 7200 # Longer TTL (2 hours)

# Higher throughput for multiple tenants
batch_size = 64         # Larger batches
timeout_seconds = 60     # Longer timeout for large batches
max_retries = 5         # More retries for reliability

[rag.chunking]
# Consistent chunking across all tenants
strategy = "sliding_window"
chunk_size = 512
overlap = 128           # More overlap for better context
max_chunk_size = 2048
min_chunk_size = 100

[rag.cache]
# Larger caches for multi-tenant scenarios
search_cache_enabled = true
search_cache_size = 10000       # Cache more queries
search_cache_ttl_seconds = 600  # 10 minutes

document_cache_enabled = true
document_cache_size_mb = 500    # Larger cache for multiple tenants

# Multi-tenant specific settings (future expansion)
[rag.multi_tenant_settings]
# Per-tenant vector limits
max_vectors_per_tenant = 100000

# Tenant lifecycle
tenant_ttl_hours = 168  # 7 days default retention
auto_cleanup = true     # Automatically remove expired tenants

# Isolation level
strict_isolation = true # No cross-tenant operations allowed

# Resource limits per tenant
max_concurrent_operations = 10
rate_limit_per_minute = 100