# Development Configuration Profile
# Optimized for local development with debugging features
# Verbose logging, full stdlib, OpenAI/Anthropic providers

default_engine = "lua"

[engines.lua]
stdlib_level = "full"

[providers]
default_provider = "openai"

[providers.providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
default_model = "gpt-4"
temperature = 0.7
max_tokens = 4000
timeout_seconds = 60

[providers.providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-3-5-sonnet-20241022"
temperature = 0.7
max_tokens = 4000
timeout_seconds = 60

[runtime]
log_level = "debug"
