# Minimal Configuration Profile
# Bare minimum settings for basic llmspell operation
# No providers, no RAG, minimal logging

default_engine = "lua"

[engines.lua]
stdlib_level = "basic"

[runtime]
log_level = "warn"
