# Providers Profile
# Simple OpenAI/Anthropic setup for agent examples
# Replaces: example-providers.toml, cookbook.toml
# Used by: 02-first-agent.lua, agent-basics.lua, multi-agent-coordination.lua

default_engine = "lua"

[engines.lua]
stdlib = "All"

[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
default_model = "gpt-3.5-turbo"
temperature = 0.7
max_tokens = 2000
timeout_seconds = 60

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-3-haiku-20240307"
temperature = 0.7
max_tokens = 2000
timeout_seconds = 60

[runtime]
log_level = "info"
