# Development RAG Configuration Profile
# Optimized for local RAG development and testing
# Fast iteration, debugging features, minimal resources

default_engine = "lua"

[engines.lua]
stdlib = "All"

[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
default_model = "gpt-3.5-turbo"
temperature = 0.7
max_tokens = 2000

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
default_model = "claude-3-haiku-20240307"
temperature = 0.7
max_tokens = 2000

[rag]
enabled = true
multi_tenant = false

[rag.vector_storage]
dimensions = 384
backend = "hnsw"
max_memory_mb = 512

[rag.vector_storage.hnsw]
m = 8
ef_construction = 50
ef_search = 25
max_elements = 10000
metric = "cosine"
allow_replace_deleted = true
num_threads = 2

[rag.embedding]
default_provider = "openai"
cache_enabled = false
cache_size = 100
cache_ttl_seconds = 60
batch_size = 4
timeout_seconds = 10
max_retries = 1

[rag.chunking]
strategy = "sliding_window"
chunk_size = 256
overlap = 32
max_chunk_size = 1024
min_chunk_size = 50

[rag.cache]
search_cache_enabled = false
search_cache_size = 10
search_cache_ttl_seconds = 30
document_cache_enabled = false
document_cache_size_mb = 10

[rag.debug]
enable_debug_logging = true
log_all_operations = true
save_debug_dumps = true
debug_dump_path = "./debug/rag"

[runtime]
log_level = "debug"
