# State Persistence Profile
# Enables State global with memory backend
# Replaces: basic.toml, state-enabled.toml
# Used by: state-persistence.lua, state-management.lua, 04-handle-errors.lua

default_engine = "lua"

[engines.lua]
stdlib = "All"

[runtime]
log_level = "info"

[runtime.state_persistence]
enabled = true
backend_type = "memory"
max_state_size_bytes = 10_000_000  # 10MB
migration_enabled = false
backup_enabled = false
