# Docker Compose v3.8 compatible (version field deprecated in v2)

# Docker Compose fleet orchestration for LLMSpell kernels
# Each service is an independent kernel with its own runtime

services:
  # Lua kernel with OpenAI configuration
  kernel-lua-openai:
    image: llmspell:latest
    container_name: llmspell-kernel-lua-openai
    command: kernel start --daemon --port 9555
    ports:
      - "9555:9555"
    volumes:
      - ./configs/openai.toml:/etc/llmspell/config.toml:ro
      - ./connection-files:/var/lib/llmspell/connections
      - ./logs/kernel-lua-openai:/var/log/llmspell
    environment:
      LLMSPELL_CONFIG: /etc/llmspell/config.toml
      LLMSPELL_CONNECTION_FILE: /var/lib/llmspell/connections/kernel-lua-openai.json
      KERNEL_ID: kernel-lua-openai
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9555"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - llmspell-network

  # Lua kernel with Anthropic configuration
  kernel-lua-anthropic:
    image: llmspell:latest
    container_name: llmspell-kernel-lua-anthropic
    command: kernel start --daemon --port 9556
    ports:
      - "9556:9556"
    volumes:
      - ./configs/anthropic.toml:/etc/llmspell/config.toml:ro
      - ./connection-files:/var/lib/llmspell/connections
      - ./logs/kernel-lua-anthropic:/var/log/llmspell
    environment:
      LLMSPELL_CONFIG: /etc/llmspell/config.toml
      LLMSPELL_CONNECTION_FILE: /var/lib/llmspell/connections/kernel-lua-anthropic.json
      KERNEL_ID: kernel-lua-anthropic
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9556"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - llmspell-network

  # JavaScript kernel (when Phase 14 is ready)
  kernel-javascript:
    image: llmspell:latest
    container_name: llmspell-kernel-javascript
    command: kernel start --daemon --port 9557 --language javascript
    ports:
      - "9557:9557"
    volumes:
      - ./configs/javascript.toml:/etc/llmspell/config.toml:ro
      - ./connection-files:/var/lib/llmspell/connections
      - ./logs/kernel-javascript:/var/log/llmspell
    environment:
      LLMSPELL_CONFIG: /etc/llmspell/config.toml
      LLMSPELL_CONNECTION_FILE: /var/lib/llmspell/connections/kernel-javascript.json
      KERNEL_ID: kernel-javascript
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9557"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - llmspell-network
    profiles:
      - javascript  # Only start when explicitly requested

  # Development/debug kernel with more resources
  kernel-dev:
    image: llmspell:latest
    container_name: llmspell-kernel-dev
    command: kernel start --daemon --port 9558 --trace debug
    ports:
      - "9558:9558"
    volumes:
      - ./configs/dev.toml:/etc/llmspell/config.toml:ro
      - ./connection-files:/var/lib/llmspell/connections
      - ./logs/kernel-dev:/var/log/llmspell
      # Mount local code for development
      - ../examples:/workspace/examples:ro
    environment:
      LLMSPELL_CONFIG: /etc/llmspell/config.toml
      LLMSPELL_CONNECTION_FILE: /var/lib/llmspell/connections/kernel-dev.json
      KERNEL_ID: kernel-dev
      RUST_LOG: debug
    restart: "no"  # Don't auto-restart dev kernel
    mem_limit: 2g
    cpus: 1.0
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9558"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - llmspell-network
    profiles:
      - dev  # Only start in dev mode

  # Fleet registry service (optional, for service discovery)
  fleet-registry:
    image: nginx:alpine
    container_name: llmspell-fleet-registry
    ports:
      - "9550:80"
    volumes:
      - ./connection-files:/usr/share/nginx/html:ro
      - ./fleet-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - llmspell-network
    profiles:
      - registry

networks:
  llmspell-network:
    driver: bridge

volumes:
  connection-files:
  logs: