# Knowledge Base Application Configuration
# Personal knowledge management system with RAG

[runtime]
name = "knowledge-base"
description = "Personal knowledge base with semantic search and retrieval"

# Provider configuration for embeddings and LLM
[providers.openai]
name = "openai"
api_key_env = "OPENAI_API_KEY"
api_base = "https://api.openai.com/v1"
default_model = "gpt-4o-mini"
timeout_seconds = 30

[providers.anthropic]
name = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
api_base = "https://api.anthropic.com/v1"
default_model = "claude-3-haiku-20240307"
timeout_seconds = 30

# Tools for knowledge management
[tools]
file_operations = { enabled = true }
text_manipulator = { enabled = true }
web_search = { enabled = true }
http_request = { enabled = true }
pdf_processor = { enabled = true }

# Workflow configuration
[workflows]
enabled = true
max_concurrent = 3
timeout_seconds = 120

# State for knowledge persistence
[state]
enabled = true
persistence_path = "/tmp/knowledge-base-state"

# Sessions for knowledge context
[sessions]
enabled = true
auto_save = true

# Events for tracking knowledge updates
[events]
enabled = true
log_level = "info"

# RAG configuration for knowledge storage
[rag]
enabled = true
provider = "openai"
embedding_model = "text-embedding-ada-002"
vector_dimensions = 1536
default_collection = "personal_knowledge"
chunk_size = 500
chunk_overlap = 100
persistence_path = "/tmp/knowledge-base-rag"
max_vectors = 10000
search_threshold = 0.6