# Personal Assistant Application Configuration
# AI-powered personal productivity assistant with RAG

[runtime]
name = "personal-assistant"
description = "AI personal assistant with task management and knowledge retrieval"

# Multi-provider configuration for flexibility
[providers.openai]
name = "openai"
api_key_env = "OPENAI_API_KEY"
api_base = "https://api.openai.com/v1"
default_model = "gpt-4o-mini"
timeout_seconds = 60

[providers.anthropic]
name = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
api_base = "https://api.anthropic.com/v1"
default_model = "claude-3-haiku-20240307"
timeout_seconds = 60

# Comprehensive tool set for personal assistance
[tools]
file_operations = { enabled = true }
text_manipulator = { enabled = true }
web_search = { enabled = true }
http_request = { enabled = true }
datetime_handler = { enabled = true }
calculator = { enabled = true }
task_manager = { enabled = true }

# Workflow configuration for complex tasks
[workflows]
enabled = true
max_concurrent = 4
timeout_seconds = 180

# State management for continuity
[state]
enabled = true
persistence_path = "/tmp/personal-assistant-state"

# Session management for context
[sessions]
enabled = true
auto_save = true
max_sessions = 10

# Events for activity tracking
[events]
enabled = true
log_level = "info"

# RAG for personal knowledge and context
[rag]
enabled = true
provider = "openai"
embedding_model = "text-embedding-ada-002"
vector_dimensions = 1536
default_collection = "personal_assistant"
chunk_size = 400
chunk_overlap = 80
persistence_path = "/tmp/personal-assistant-rag"
max_vectors = 20000
search_threshold = 0.65