[package]
name = "embed-llmspell-example"
version = "0.1.0"
edition = "2021"

[dependencies]
llmspell-bridge = { path = "../../../../llmspell-bridge" }
llmspell-core = { path = "../../../../llmspell-core" }
llmspell-tools = { path = "../../../../llmspell-tools" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }