# WebApp Creator Configuration - New llmspell-config Schema
# Matches the centralized configuration structure from llmspell-config crate

# Default script engine
default_engine = "lua"

# Engine configurations
[engines.lua]
stdlib = "Safe"
max_memory_bytes = 100000000
debug = false
package_paths = []

[engines.javascript]
strict_mode = true
max_heap_size_bytes = 100000000
enable_console = true
module_resolution = "Node"

# Provider configurations
[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"

# Global runtime configuration
[runtime]
max_concurrent_scripts = 5
script_timeout_seconds = 300
enable_streaming = true

[runtime.security]
allow_file_access = true
allow_network_access = true
allow_process_spawn = false
max_memory_bytes = 104857600
max_execution_time_ms = 300000

[runtime.state_persistence]
backend_type = "memory"

[runtime.state_persistence.flags.core]
enabled = true
migration_enabled = false

[runtime.state_persistence.flags.backup]
backup_enabled = false

[runtime.sessions]
enabled = true
persistence = true
storage_path = "./webapp-sessions"
session_timeout_minutes = 60
max_sessions = 100

# Tool configurations
[tools.file_operations]
allowed_paths = [
    "/tmp",
    "/tmp/webapp-projects", 
    "/Users/spuri/projects/lexlapax/rs-llmspell/examples/script-users/applications/webapp-creator/generated",
    "/Users/spuri/projects/webapp-output"
]
max_file_size = 52428800
atomic_writes = true

[tools.web_search]
rate_limit_per_minute = 30
max_results_per_query = 10
default_provider = "duckduckgo"
providers = []

[tools.http_request]
timeout_seconds = 30
max_redirects = 5
user_agent = "llmspell-webapp-creator/1.0"

# Custom tool configurations
[tools.custom.json_processor]
max_depth = 50
max_items = 10000

[tools.custom.text_manipulator]
max_input_size = 1048576

[tools.custom.code_analyzer]
enabled = true

[tools.custom.api_tester]
enabled = true

[tools.custom.webhook_caller]
enabled = true