# WebApp Creator Configuration - Corrected Schema
# Matches the exact llmspell-config structure from source code

# Default script engine
default_engine = "lua"

# Engine configurations - correct field names and values
[engines.lua]
stdlib = "Standard"  # Options: None, Basic, Standard, All
max_memory_bytes = 100000000
enable_debug = false
timeout_ms = 30000
security_level = "Safe"  # Options: Safe, Privileged, Unrestricted

[engines.javascript]
strict_mode = true
max_heap_size_bytes = 100000000
enable_console = true
timeout_ms = 30000
security_level = "Safe"

# Provider configurations - clean hierarchy
[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"
timeout_seconds = 60

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"
timeout_seconds = 60

# Global runtime configuration - exact field names from lib.rs
[runtime]
max_concurrent_scripts = 5
script_timeout_seconds = 300
enable_streaming = true

[runtime.security]
allow_file_access = true
allow_network_access = true
allow_process_spawn = false
max_memory_bytes = 104857600
max_execution_time_ms = 300000

# State persistence - flattened structure
[runtime.state_persistence]
enabled = true
backend_type = "memory"
max_state_size_bytes = 10000000
migration_enabled = false
backup_enabled = false
backup_on_migration = false

# Session management - exact field names from lib.rs SessionConfig
[runtime.sessions]
enabled = true
max_sessions = 100
max_artifacts_per_session = 1000
artifact_compression_threshold = 10240
session_timeout_seconds = 3600
storage_backend = "memory"

# Tool configurations - exact field names from tools.rs
[tools.file_operations]
allowed_paths = [
    "/tmp",
    "/tmp/webapp-projects", 
    "/Users/spuri/projects/lexlapax/rs-llmspell/examples/script-users/applications/webapp-creator/generated",
    "/Users/spuri/projects/webapp-output"
]
max_file_size = 52428800
atomic_writes = true
max_depth = 10
allowed_extensions = []
blocked_extensions = ["exe", "dll", "so", "dylib"]
validate_file_types = true

[tools.web_search]
rate_limit_per_minute = 30
allowed_domains = ["*"]
blocked_domains = []
max_results = 10
timeout_seconds = 30
user_agent = "llmspell-webapp-creator/1.0"

[tools.http_request]
allowed_hosts = ["*"]
blocked_hosts = ["localhost", "127.0.0.1", "0.0.0.0"]
max_request_size = 10000000
timeout_seconds = 30
max_redirects = 5

[tools.http_request.default_headers]
"User-Agent" = "llmspell-webapp-creator/1.0"

# Custom tool configurations via flattened HashMap
[tools.custom.json_processor]
max_depth = 50
max_items = 10000

[tools.custom.text_manipulator]
max_input_size = 1048576

[tools.custom.code_analyzer]
enabled = true

[tools.custom.api_tester]
enabled = true

[tools.custom.webhook_caller]
enabled = true