# WebApp Creator Configuration - Corrected Schema
# Matches the exact llmspell-config structure from source code

# Default script engine
default_engine = "lua"

# Engine configurations - These use sensible defaults if omitted
# [engines.lua]
# stdlib = "Standard"  # Default
# max_memory_bytes = 50000000  # Default: 50MB
# enable_debug = false  # Default
# timeout_ms = 30000  # Default: 30 seconds
# security_level = "Safe"  # Default

# [engines.javascript]
# strict_mode = true  # Default
# max_heap_size_bytes = 50000000  # Default: 50MB
# enable_console = true  # Default
# timeout_ms = 30000  # Default: 30 seconds
# security_level = "Safe"  # Default

# Provider configurations - clean hierarchy
[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"
timeout_seconds = 60

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"
timeout_seconds = 60

# Global runtime configuration - exact field names from lib.rs
[runtime]
max_concurrent_scripts = 5
script_timeout_seconds = 300
enable_streaming = true

[runtime.security]
allow_file_access = true
allow_network_access = true
allow_process_spawn = false
max_memory_bytes = 104857600
max_execution_time_ms = 300000

# State persistence - flattened structure
[runtime.state_persistence]
enabled = true
backend_type = "memory"
max_state_size_bytes = 10000000
migration_enabled = false
backup_enabled = false
backup_on_migration = false

# Session management - exact field names from lib.rs SessionConfig
[runtime.sessions]
enabled = true
max_sessions = 100
max_artifacts_per_session = 1000
artifact_compression_threshold = 10240
session_timeout_seconds = 3600
storage_backend = "memory"

# Tool configurations - These sections can be completely omitted if defaults are acceptable
[tools.file_operations]
allowed_paths = [
    "*"
]
atomic_writes = true
max_file_size = 10485760

# [tools.web_search]  
# [tools.http_request]

# Custom tool configurations via flattened HashMap
[tools.custom.json_processor]
max_depth = 50
max_items = 10000

[tools.custom.text_manipulator]
max_input_size = 1048576

[tools.custom.code_analyzer]
enabled = true

[tools.custom.api_tester]
enabled = true

[tools.custom.webhook_caller]
enabled = true