# Workflow Automation Hub Configuration
# Blueprint v2.0 compliant workflow orchestration system

# Default engine
default_engine = "lua"

# Engine configuration (required)
[engines]
default = "lua"

[engines.lua]
security_level = "safe"
max_memory_mb = 512
timeout_ms = 60000

[engines.javascript]
security_level = "safe"
max_memory_mb = 512
timeout_ms = 60000

# Provider configuration
[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"
temperature = 0.3
max_tokens = 500

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"
temperature = 0.2
max_tokens = 400

# Runtime configuration
[runtime]
log_level = "info"
max_execution_time_ms = 60000

# State persistence
[state]
enabled = true
state_dir = "/tmp/workflow-state"

# Monitoring settings
[monitoring]
check_interval_ms = 1000
max_retries = 3
timeout_ms = 30000