[alias]
# Test aliases (use cargo test directly with feature flags)
test-all = "test --workspace"
test-unit = "test -p llmspell-testing --features unit-tests --test unit"
test-integration = "test -p llmspell-testing --features integration-tests --test integration"
test-agent = "test -p llmspell-testing --features agent-tests --test agents"
test-scenario = "test -p llmspell-testing --features scenario-tests --test scenarios"
test-lua = "test -p llmspell-testing --features lua-tests --test lua"
bench-all = "bench -p llmspell-testing"

# Quality check shortcuts
fmt-check = "fmt --all -- --check"
clippy-all = "clippy --workspace --all-features -- -D warnings"
doc-all = "doc --workspace --no-deps --all-features --document-private-items"

# Build shortcuts
build-all = "build --workspace --all-features"
build-release = "build --workspace --all-features --release"