# Professional Layer Configuration - Process Orchestrator
# Full enterprise process orchestration with maximum platform capabilities

[runtime]
name = "process-orchestrator"
description = "Professional enterprise process orchestration"
debug = false
performance_monitoring = true

# Multiple providers with load balancing and fallback
[providers.openai]
name = "openai"
api_key_env = "OPENAI_API_KEY"
api_base = "https://api.openai.com/v1"
default_model = "gpt-4o"
timeout_seconds = 90
retry_attempts = 3
max_concurrent_requests = 10

[providers.anthropic]
name = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
api_base = "https://api.anthropic.com/v1"
default_model = "claude-3-5-sonnet-20241022"
timeout_seconds = 90
retry_attempts = 3
max_concurrent_requests = 10

[providers.azure]
name = "azure"
api_key_env = "AZURE_OPENAI_API_KEY"
api_base_env = "AZURE_OPENAI_ENDPOINT"
deployment_name = "gpt-4"
api_version = "2024-02-15-preview"
timeout_seconds = 90

# Professional orchestration tools
[tools]
file_operations = { enabled = true }
http_request = { enabled = true, rate_limit = 100 }
webhook_caller = { enabled = true, rate_limit = 50 }
database_connector = { enabled = true }
json_processor = { enabled = true }
text_manipulator = { enabled = true }
data_validation = { enabled = true }
api_tester = { enabled = true }
pdf_processor = { enabled = true }
csv_processor = { enabled = true }
encryption_utils = { enabled = true }

# Advanced workflow orchestration
[workflows]
enabled = true
max_concurrent = 20
timeout_seconds = 600
retry_attempts = 3
error_handling = "graceful"
dead_letter_queue = true
circuit_breaker_enabled = true
circuit_breaker_threshold = 5

# Enterprise state management
[state]
enabled = true
persistence_enabled = true
storage_backend = "postgresql"
connection_string_env = "DATABASE_URL"
cache_size_mb = 100
backup_enabled = true
backup_interval_minutes = 15
encryption_enabled = true
versioning_enabled = true

# Professional session management
[sessions]
enabled = true
max_sessions = 500
session_timeout_minutes = 1440  # 24 hours
artifact_storage = true
artifact_path = "./data/orchestrator-artifacts"
thread_tracking = true
session_persistence = true
cross_session_state = true

# Enterprise event system
[events]
enabled = true
buffer_size = 10000
export_method = "kafka"
kafka_brokers = ["kafka1:9092", "kafka2:9092"]
topic = "process-orchestration-events"
compression = "snappy"
batch_size = 100
export_interval_seconds = 30

# Professional hooks system
[hooks]
enabled = true
max_hooks = 50
hook_timeout_seconds = 30

[[hooks.pre_process]]
name = "validation_hook"
script = "/hooks/validate_process.lua"
enabled = true
async = true

[[hooks.post_process]]
name = "audit_hook"
script = "/hooks/audit_process.lua"
enabled = true
async = true

[[hooks.on_error]]
name = "error_recovery"
script = "/hooks/error_recovery.lua"
enabled = true
retry_count = 3

# Process orchestration rules
[orchestration]
max_process_depth = 5
parallel_process_limit = 10
conditional_routing = true
dynamic_routing = true
process_templates_path = "./templates/processes"
business_rules_path = "./rules"

# Business rules engine
[business_rules]
enabled = true
rules_engine = "drools"
rules_path = "./rules"
hot_reload = true
validation_strict = true

# Performance monitoring
[monitoring]
metrics_enabled = true
metrics_endpoint = "/metrics"
prometheus_enabled = true
apm_enabled = true
apm_service_name = "process-orchestrator"
tracing_enabled = true
trace_sample_rate = 0.1

# Security settings
[security]
authentication_required = true
auth_method = "oauth2"
token_endpoint_env = "OAUTH_TOKEN_ENDPOINT"
encryption_at_rest = true
audit_logging = true
rate_limiting = true
rate_limit_per_minute = 1000

# SLA configuration
[sla]
approval_workflow_timeout_minutes = 30
data_migration_timeout_hours = 4
quality_assurance_timeout_hours = 2
incident_response_timeout_minutes = 15
escalation_enabled = true
escalation_webhook = "https://api.company.com/escalate"