[package]
name = "llmspell-kernel"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Jupyter-compatible execution kernel for LLMSpell"

[dependencies]
# Core dependencies
anyhow = "1.0"
tokio = { version = "1.41", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.11", features = ["v4", "serde"] }
async-trait = "0.1"

# Internal crates (minimal initial dependencies)
llmspell-bridge = { path = "../llmspell-bridge" }
llmspell-config = { path = "../llmspell-config" }
llmspell-debug = { path = "../llmspell-debug" }
llmspell-sessions = { path = "../llmspell-sessions" }
llmspell-state-persistence = { path = "../llmspell-state-persistence" }

# ZeroMQ and Jupyter (to be uncommented in Task 9.8.5)
# zmq = "0.10"
# jupyter-protocol = { git = "https://github.com/llmspell/jupyter-protocol" }
# hmac = "0.12"
# sha2 = "0.10"
# hex = "0.4"

[[bin]]
name = "llmspell-kernel"
path = "src/bin/llmspell-kernel.rs"

[dev-dependencies]
tempfile = "3.14"
tokio-test = "0.4"

[lints]
workspace = true
