# Research Assistant Application Configuration
# This config enables the academic research features

# Default script engine
default_engine = "lua"

# Engine configuration
[engines.lua]
security_level = "safe"

[engines.javascript]
security_level = "safe"

# Runtime configuration
[runtime]
log_level = "info"

# Provider configuration
[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"

[state]
backend = "memory"
auto_save = false

[tools]
enabled = [
    "file_operations",
    "pdf_processor",
    "citation_formatter", 
    "graph_builder",
    "json_processor",
    "text_manipulator"
]

[logging]
level = "info"
format = "pretty"