[package]
name = "custom-tool-example"
version = "0.1.0"
edition = "2021"

[dependencies]
llmspell-core = { path = "../../../../llmspell-core" }
llmspell-bridge = { path = "../../../../llmspell-bridge" }
llmspell-tools = { path = "../../../../llmspell-tools" }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }