# LLMSpell Configuration File
# This is an example configuration showing all available options

# Default script engine to use (lua, javascript, python)
default_engine = "lua"

# Engine-specific configurations
[engines.lua]
stdlib_level = "full"          # stdlib access level: none, basic, full
sandbox_mode = false           # enable Lua sandbox mode
memory_limit = 52428800        # 50MB memory limit
max_instructions = 1000000     # max VM instructions
allow_ffi = false              # allow foreign function interface
allow_io = false               # allow I/O operations
allow_os = false               # allow OS operations
allow_debug = false            # allow debug library
custom_modules = []            # additional Lua modules to load

[engines.javascript]
module_resolution = "node"     # module resolution: node, deno, browser
allow_eval = false             # allow eval() function
allow_timers = true            # allow setTimeout/setInterval
allow_console = true           # allow console API
memory_limit = 52428800        # 50MB memory limit
max_event_loop_ticks = 10000   # max event loop iterations
typescript = false             # enable TypeScript support
jsx = false                    # enable JSX support
custom_globals = {}            # additional global variables

# Provider configurations
[providers]
default_provider = "openai"    # default LLM provider to use

[providers.providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4"
max_tokens = 2048

[providers.providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"
max_tokens = 4096

# Global runtime settings
[runtime]
max_concurrent_scripts = 10    # maximum scripts running in parallel
script_timeout_seconds = 300   # 5 minutes timeout per script
enable_streaming = true        # enable streaming responses by default

# Security settings
[runtime.security]
allow_file_access = false      # allow scripts to access filesystem
allow_network_access = true    # allow scripts to make network requests
allow_process_spawn = false    # allow scripts to spawn processes
max_memory_bytes = 52428800    # 50MB max memory per script
max_execution_time_ms = 300000 # 5 minutes max execution time