# Document Intelligence System Configuration
# Purpose: Extract insights from documents with Q&A and knowledge management
# Prerequisites: OPENAI_API_KEY or ANTHROPIC_API_KEY environment variables
# Version: 0.8.0

default_engine = "lua"

[engines.lua]
security_level = "safe"

[engines.javascript]
security_level = "safe"

[runtime]
log_level = "info"

[providers]
default_provider = "openai"

[providers.openai]
provider_type = "openai"
api_key_env = "OPENAI_API_KEY"
model = "gpt-4o-mini"

[providers.anthropic]
provider_type = "anthropic"
api_key_env = "ANTHROPIC_API_KEY"
model = "claude-3-haiku-20240307"